# Develop Branch Deployment Workflow

name: Develop Branch (Unstable Release) Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push (protection requires pull request) events to the develop branch
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Globally scoped environment variables
env:
  BUILD_CONFIGURATION: Release
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      # Install GitTools
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'

      # Determine SemVer with GitVersion
      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15
        with:
          useConfigFile: true
          
  build:
    needs: setup
    uses: CamecaAPT/workflows/.github/workflows/build.yml@main
    with:
      build-configuration: $env:BUILD_CONFIGURATION
      version: $env:GitVersion_SemVer
  
  pack:
    needs: [setup, build]
    uses: CamecaAPT/workflows/.github/workflows/pack.yml@main
    with:
      build-configuration: $env:BUILD_CONFIGURATION
      version: $env:GitVersion_SemVer
  
  push:
    needs: [setup, pack]
    uses: CamecaAPT/workflows/.github/workflows/push-azure.yml@main
    with:
      artifact-feed-url: ${{ vars.FEED_EXTENSION_DEVELOPMENT_PREVIEW }}
    secrets:
      azure-pat: ${{ secrets.AZURE_PACKAGE_READ_WRITE }}
