# Develop Branch Deployment Workflow

name: Develop Branch (Unstable Release) Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push (protection requires pull request) events to the develop branch
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # Job scoped environment variables
    env:
      BUILD_CONFIGURATION: Release

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          source-url: https://pkgs.dev.azure.com/cameca/Extensions/_packaging/extensions-dev-preview/nuget/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.AZURE_PACKAGE_READ_WRITE }}

      # Install GitTools
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.11
        with:
          versionSpec: '5.x'

      # Determine SemVer with GitVersion
      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0.9.11
        with:
          useConfigFile: true

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore
      
      # Build
      - name: Build
        run: >
          dotnet build
          --no-restore
          --configuration $env:BUILD_CONFIGURATION
          /p:Version=$env:GitVersion_SemVer
          --nologo
      
      # Test (if present)
      - name: Test
        run: >
          dotnet test
          --no-build
          --configuration $env:BUILD_CONFIGURATION
          --verbosity normal
          --nologo
      
      # Create the preview package
      - name: Pack
        run: >
          dotnet pack
          --no-build
          --configuration $env:BUILD_CONFIGURATION
          --include-symbols
          /p:Version=$env:GitVersion_SemVer
          --output .

      - name: Push (Package)
        run: >
          dotnet nuget push
          *.nupkg
          --api-key az
          --skip-duplicate
          
      - name: Push (Symbols Package)
        run: >
          dotnet nuget push
          *.snupkg
          --api-key az
          --skip-duplicate
